project:
  type: website
  output-dir: docs
website:
  title: "Oberon Citizen Science Network"
  favicon: assets/favicon.ico
  page-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/oberon-citizen-science/website
          - text: Report an Error
            url:  https://github.com/oberon-citizen-science/website/issues
    left:
      - text: "About"
        menu:
          - text: "Welcome to OCSN"
            href: .
          - text: "What is Citizen Science?"
            href: what_is_citizen_science.ymd
          - text: "Mission Statement"
            href: ocsn_mission_statement.ymd
          - text: "Articles of Association"
            href: ocsn_articles_of_association.ymd
          - text: "Code of Conduct"
            href: ocsn_code_of_conduct.ymd
          - text: "Privacy Policy"
            href: ocsn_privacy_policy.qmd
      - text: "Potential Activities"
        menu:
          - text: "FrogID"
            href: frogid.qmd
          - text: "Astronomy"
            href: astronomy.qmd
          - text: "Wind farms"
            href: wind_farms.qmd
      - text: "Sensor Networks"
        menu:
          - text: "Seismic and infrasound monitoring"
            href: shake_and_boom.qmd
          - text: "Meteor detection and tracking"
            href: meteors.qmd
          - text: "Bird call detection and counting"
            href: birdnet.qmd
          - text: "Local weather monitoring"
            href: local_weather.qmd
          - text: "LoRaWAN and NB-IoT"
            href: nb_networks.qmd
      - text: "News"
        href: news.qmd
      - text: "Blog posts"
        href: blog.qmd
      - text: "Register your interest"
        href: register_interest.qmd
  sidebar:
    style: "floating"
    search: false
    pinned: true
    logo: assets/ocsn_mascots.png
    contents:
      - section: "Introductions"
        contents:
          - text: "Welcome to OCSN"
            href: index.qmd
          - text: "What is Citizen Science?"
            href: what_is_citizen_science.qmd
          - text: "Mission Statement"
            href: ocsn_mission_statement.qmd
          - text: "Articles of Association"
            href: ocsn_articles_of_association.qmd
          - text: "Code of Conduct"
            href: ocsn_code_of_conduct.qmd
          - text: "Privacy Policy"
            href: ocsn_privacy_policy.qmd
          - text: "Register your interest"
            href: register_interest.qmd
      - section: "Potential Activities"
        contents:
          - text: "FrogID"
            href: frogid.qmd
          - text: "Astronomy"
            href: astronomy.qmd
      - section: "Potential Sensor Networks"
        contents:
          - text: "Seismic and infrasound monitoring"
            href: shake_and_boom.qmd
          - text: "Meteor detection and tracking"
            href: meteors.qmd
          - text: "Bird call detection and counting"
            href: birdnet.qmd
          - text: "Local weather monitoring"
            href: local_weather.qmd
          - text: "LoRaWAN and NB-IoT"
            href: nb_networks.qmd
fig-cap-location: bottom
reference-location: section
footnotes-hover: true
format:
  html:
    theme: united
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true




