project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  title: "Oberon Citizen Science Network"
  favicon: assets/favicon.ico
  page-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    tools:
      - icon: envelope-at
        text: Email
        href: mailto:oberon.citizen.science@gmail.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/oberon-citizen-science/website
          - text: Report an Error
            url:  https://github.com/oberon-citizen-science/website/issues
    left:
      - text: "About"
        menu:
          - text: "Welcome to OCSN"
            href: .
          - text: "What is Citizen Science?"
            href: what_is_citizen_science.qmd
          - text: "Mission Statement"
            href: ocsn_mission_statement.qmd
          - text: "Articles of Association"
            href: ocsn_articles_of_association.qmd
          - text: "Code of Conduct"
            href: ocsn_code_of_conduct.qmd
          - text: "Privacy Policy"
            href: ocsn_privacy_policy.qmd
      - text: "Activities"
        menu:
          - text: "FrogID"
            href: frogid.qmd
          - text: "Platypus & rakali surveys"
            href: platypus_rakali.qmd
          - text: "Koala surveys"
            href: koalas.qmd
          - text: "Astronomy"
            href: astronomy.qmd
          - text: "Citizen science and wind farms"
            href: wind_farms.qmd
      - text: "Sensor Networks"
        menu:
          - text: "Seismic and infrasound monitoring"
            href: shake_and_boom.qmd
          - text: "Meteor detection and tracking"
            href: meteors.qmd
          - text: "Bird call detection and counting"
            href: birdnet.qmd
          - text: "Eco-acoustics"
            href: ecoacoustics.qmd
          - text: "Local weather monitoring"
            href: local_weather.qmd
          - text: "Air quality monitoring"
            href: ocsn_air_quality_monitoring.qmd
          - text: "LoRaWAN and NB-IoT"
            href: nb_networks.qmd
      - text: "News"
        href: news.qmd
      - text: "Blog posts"
        href: blog.qmd
      - text: "All-sky camera"
        href: https://www.ocsn-allsky.net/indi-allsky/
      - text: "Gallery"
        href: ocsn_gallery.qmd
      - text: "Register your interest"
        href: register_interest.qmd
  sidebar:
    style: "floating"
    search: false
    pinned: true
    logo: assets/ocsn_mascots.png
    contents:
      - section: "Introductions"
        contents:
          - text: "Welcome to OCSN"
            href: index.qmd
          - text: "What is Citizen Science?"
            href: what_is_citizen_science.qmd
          - text: "Mission Statement"
            href: ocsn_mission_statement.qmd
          - text: "Articles of Association"
            href: ocsn_articles_of_association.qmd
          - text: "Code of Conduct"
            href: ocsn_code_of_conduct.qmd
          - text: "Privacy Policy"
            href: ocsn_privacy_policy.qmd
          - text: "Register your interest"
            href: register_interest.qmd
          - icon: envelope-at
            text: Email
            href: mailto:oberon.citizen.science@gmail.com
      - section: "Activities"
        contents:
          - text: "FrogID"
            href: frogid.qmd
          - text: "Platypus & rakali surveys"
            href: platypus_rakali.qmd
          - text: "Koala surveys"
            href: koalas.qmd
          - text: "Astronomy"
            href: astronomy.qmd
          - section: "Wind farms"
            contents:
            - text: "Citizen science and wind farms"
              href: wind_farms.qmd
            - text: "Visualising the proposed Pines Wind Farm"
              href: pines_gep_model_oct_2024.qmd
      - section: "Sensor Networks"
        contents:
          - text: "Seismic and infrasound monitoring"
            href: shake_and_boom.qmd
          - text: "Meteor detection and tracking"
            href: meteors.qmd
          - text: "All-sky camera (beta)"
            href: https://www.ocsn-allsky.net/indi-allsky/
          - text: "Bird call detection and counting"
            href: birdnet.qmd
          - text: "Eco-acoustics"
            file: ecoacoustics.qmd
          - text: "Local weather monitoring"
            href: local_weather.qmd
          - text: "Air quality monitoring"
            href: ocsn_air_quality_monitoring.qmd
          - text: "LoRaWAN and NB-IoT"
            href: nb_networks.qmd
fig-cap-location: bottom
reference-location: section
footnotes-hover: true
format:
  html:
    theme:
      light: united
      dark: darkly
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true




