project:
  type: website
  output-dir: docs
website:
  title: "Oberon Citizen Science Network"
  favicon: assets/favicon.ico
  page-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/oberon-citizen-science/website
          - text: Report an Error
            url:  https://github.com/oberon-citizen-science/website/issues
    left:
      - text: "About"
        menu:
          - text: "Introduction"
            file: index.html
          - text: "What is Citizen Science?"
            file: what_is_citizen_science.html
          - text: "Mission Statement"
            file: ocsn_mission_statement.html
          - text: "Articles of Association"
            file: ocsn_articles_of_association.html
          - text: "Code of Conduct"
            file: ocsn_code_of_conduct.html
          - text: "Privacy Policy"
            file: ocsn_privacy_policy.html
      - text: "Potential Activities"
        menu:
          - text: "FrogID"
            file: frogid.html
          - text: "Astronomy"
            file: astronomy.html
          - text: "Wind farms"
            file: wind_farms.html
      - text: "Sensor Networks"
        menu:
          - text: "Seismic and infrasound monitoring"
            file: shake_and_boom.html
          - text: "Meteor detection and tracking"
            file: meteor
          - text: "Bird call detection and counting"
            file: birdnet.html
          - text: "Local weather monitoring"
            file: local_weather.html
          - text: "Oberon LGA LoRaWAN"
            file: lorawan.html
      - text: "News"
        file: news.html
      - text: "Blog posts"
        file: blog_posts.html
      - text: "Register your interest"
        target: _blank
        url: https://forms.gle/6HDzYWCqcRTkBsJ69
  sidebar:
    style: "floating"
    search: false
    pinned: true
    logo: assets/ocsn_mascots.png
    contents:
      - section: "Introductions"
        contents:
          - text: "Welcome to OCSN"
            file: index.html
          - text: "What is Citizen Science?"
            file: what_is_citizen_science.html
          - text: "Mission Statement"
            file: ocsn_mission_statement.html
          - text: "Articles of Association"
            file: ocsn_articles_of_association.html
          - text: "Code of Conduct"
            file: ocsn_code_of_conduct.html
          - text: "Privacy Policy"
            file: ocsn_privacy_policy.html
      - section: "Potential Activities"
        contents:
          - text: "FrogID"
            file: frogid.html
          - text: "Astronomy"
            file: astronomy.html
      - section: "Potential Sensor Networks"
        contents:
          - text: "Seismic and infrasound monitoring"
            file: shake_and_boom.html
          - text: "Bird call detection and counting"
            file: birdnet.html
          - text: "Local weather monitoring"
            file: local_weather.html
          - text: "Oberon LGA LoRaWAN"
            file: lorawan.html
fig-cap-location: bottom
reference-location: section
footnotes-hover: true
format:
  html:
    theme: united
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true




