---
title: "OCSN Privacy Policy"
---

This Privacy Policy applies to all personal information collected by Oberon Citizen Science Network (OCSN) via the website located at https://oberon-citizen.science, via email accounts associated with OCSN and via other web and social media data collection mechanisms.

## 1. What is "personal information"?

  i) The Privacy Act 1988 (Cth) currently defines "personal information" as meaning information or an opinion about an identified individual or an individual who is reasonably identifiable:
    a) whether the information or opinion is true or not; and
    a) whether the information or opinion is recorded in a material form or not.
  i) If the information does not disclose your identity or enable your identity to be ascertained, it will in most cases not be classified as "personal information" and will not be subject to this privacy policy.

## 2. What information do we collect?

The kind of personal information that we collect from you will depend on how you use the website. The personal information which we collect and hold about you may include:

  * name
  * email address
  * phone number
  * town, suburb or area of residence (not full address)

## 3. How we collect your personal information

  i) We may collect personal information from you whenever you input such information into the website.
  i) We also collect cookies from your computer which enable us to tell when you use the website and also to help customise your website experience. As a general rule, however, it is not possible to identify you personally from our use of cookies.

## 4. Purpose of collection

  i) The purpose for which we collect personal information is to provide you with the best service experience possible on the website.
  i) We customarily disclose personal information only to our service providers who assist us in operating the website. Your personal information may also be exposed from time to time to maintenance and support personnel acting in the normal course of their duties.
  i) By using our website, you consent to the receipt of direct marketing material. We will only use your personal information for this purpose if we have collected such information direct from you, and if it is material of a type which you would reasonably expect to receive from us. We do not use sensitive personal information in direct marketing activity. Our direct marketing material will include a simple means by which you can request not to receive further communications of this nature.

## 5. Access and correction

Australian Privacy Principle 12 permits you to obtain access to the personal information we hold about you in certain circumstances, and Australian Privacy Principle 13 allows you to correct inaccurate personal information subject to certain exceptions. If you would like to obtain such access, please contact us as set out below.

## 6. Complaint procedure

If you have a complaint concerning the manner in which we maintain the privacy of your personal information, please contact us as set out below. All complaints will be considered by the OCSN nominated Privacy Officer and we may seek further information from you to clarify your concerns. If we agree that your complaint is well founded, we will, in consultation with you, take appropriate steps to rectify the problem. If you remain dissatisfied with the outcome, you may refer the matter to the Office of the Australian Information Commissioner.

## 7. How to contact us about privacy

If you have any queries, or if you seek access to your personal information, or if you have a complaint about our privacy practices, you can contact us via email at [oberon.citizen.science@gmail.com](mailto:oberon.citizen.science@gmail.com).



