---
title: "Untitled"
---

| Distance Zone           |	Description         |
|-------------------------|---------------------|
| Immediate Foreground<br>(0 to 0.8 km) | The immediate foreground extends to 800 metres from the observer. Within this distance zone, a turbine is the dominant object in the view, when the turbine blades passes its tower an audible rhythmic whooshing sound is created. Observers may have the sensation that a turbine is “looming” over them. |
| Foreground<br>(0.8 to 3.2 km) | The foreground is determined by the prominence of tree branches and trunks; the analogous parts of wind turbines are the blades and tower. The presence of individual turbines and the movement of the blades attracts and holds an observer’s attention. Turbine sounds may still be noticeable, though it will be substantially reduced as distance increases. In the foreground, some other features in the surrounding landscape may appear to have midground characteristics, even though the wind turbines clearly retain foreground characteristics |
| Near-Midground<br>(3.2 to 8.1 km) | Viewed in the near-midground, multiple visible turbines are perceived as part of a single whole. For instance, the Gestalt principles of similarity and continuity lead us to understand that wind turbines placed along a ridgeline are part of the same wind farm. At night, synchronized red flashing aviation warning lights will also be perceived as a single unit. At this distance it is possible that individual turbines may still have a dominant visual presence; blade movement may still hold a strong visual attraction. |
| Far-Midground<br>(8.1 to 16.1 km) | In the far-midground, individual turbines become subordinate to the perception of the wind energy development as a whole. The number of turbines, and the degree to which they extend across the view, determines the visual dominance. When the major portion of a turbine is visible, blade movement is still apparent, but is less able to hold the observer’s attention. In the far-midground, some other features in the surrounding landscape may appear to have background characteristics, even though the wind turbines clearly retain midground characteristics. |
| Background<br>(16.1 to 32.2 km) | Individual turbines and blade movement becomes less obvious, though the presence of a wind energy project may still be visible as part of the overall landscape. This defines the outer extent of the study area. |
