---
title: "What is Citizen Science?"
lightbox: true
---

_Wikipedia_ defines [**citizen science**](https://en.wikipedia.org/wiki/Citizen_science) as:

::: {.callout-note appearance="simple" icon=false}

##

Citizen science (also known as community science, crowd science, crowd-sourced science, civic science, participatory monitoring, or volunteer monitoring) is research conducted with participation from the general public, or amateur/non-professional researchers or participants for science, social science and many other disciplines. There are variations in the exact definition of citizen science, with different individuals and organizations having their own specific interpretations of what citizen science encompasses. Citizen science is used in a wide range of areas of study including ecology, biology and conservation, health and medical research, astronomy, media and communications and information science.
:::

Citizen science has been around since the 1980s, and today there are thousands of citizen science groups around the world, working on and participating in science projects and investigations ranging from collecting data on the local environment and wildlife to very ambitious projects such as [CubeSats](https://csps.aerospace.org/sites/default/files/2021-08/Singh_CitizenSpace_03082019.pdf)[^1].

::: {.aside}
Closely related to **citizen science** is the concept of [**open science**](https://en.wikipedia.org/wiki/Open_science). Open science is the movement to make scientific research (including publications, data, physical samples, and software) and its dissemination accessible to all levels of society, amateur or professional. Open science is transparent and accessible knowledge that is shared and developed through collaborative networks.

![Pillars of the Open Science according to UNESCO's 2021 Open Science recommendation.[^2]](assets/UNESCO-Open_science-pillars-en.png)
:::

### Citizen Science projects and activities

Traditionally citizen science projects have focussed on monitoring and collecting data on the environment and local ecologies, with an emphasis on flora and fauna (plants and animals). We see such activities as key components of the OCSN program. Some examples of such activities can be found on this web site.

However, we are also keen for OCSN to undertake some less usual projects, in particular projects which involve establishing a network of automated sensors for various things, which collect data continuously and make those data available through various platforms. On top of such data collection infrastructure, numerous secondary projects involving data analysis can be built. Such projects may be particularly attractive to schools. Some proposed sensor network projects are also described on this web site.

### All ages

The intention is for OCSN to promote, facilitate and host projects and activities which appeal to all ages, including children.[^3] Here is a cute video by the Australian Broadcasting Corporation _Behind The News_ team on young participants in citizen science initiatives.


{{< video https://youtu.be/8cv30CcsFjQ?si=IxtULDs1imSmojn2 >}}

[^1]: Sending an OCSN CubeSat into space is probably a bit ambitious at this stage, but atmospheric science projects using drones and ballons are not out-of-the-question, such as this [model CubeSat](https://learn.auststem.com.au/model-cubesat/) designed by [AustSTEM](https://learn.auststem.com.au).

[^2]: UNESCO.org, CC BY-SA 4.0, via Wikimedia Commons

[^3]: OCSN will adopt and enforce a suitable [Working With Children Policy](ocsn_working_with_children.html) covering all its activities.
